### ISSUE TITLE
Radssh hangs when executing a reboot

### ISSUE THREAD

**Issue by stuartort** [radssh/radssh#11]
RadSSH $ sudo reboot -f
Whoa, Cowboy! Are you sure you want to run the following command, Tex?
Please double check all parameters, just to be sure...
   >>> sudo reboot -f
Enter '100%' if completely sure: 100%

When I tried this on 106 nodes, I got a status that said 3/106 complete and it just hung, but nodes seemed to be restarting

When I later tried this on just 6 nodes (the last six in my cluster), the status never changed, radssh "hung" and the boxes never rebooted

@radssh

**Comment by radssh** [comment]
Able to reproduce with `reboot -f`, but not with just `reboot`. I suspect what is happening is that with the `-f` flag, the reboot process itself ,that the ssh exec_command is waiting for completion, never (or perhaps only ~3% of the time) gets a chance to complete and send the exit status code back to the ssh client side.

Probably related to https://github.com/paramiko/paramiko/issues/503 - will investigate whether RadSSH can make an effort to check on connection health, if paramiko does not.

**Comment by stuartort** [comment]
I also had  "hang" when I connected to all the nodes using radssh.  While connected, one of the nodes crashed and then when I executed a command in radssh, radssh seemed to "hang"  (not doing a reboot, just a regular command, not sure if it is related)

**Comment by radssh** [comment]
I think that additional scenario will also be helped with adding to RadSSH more robust checking of connection state, as the description of https://github.com/paramiko/paramiko/issues/503 describes a blocked read that will never return when the network connection is dropped mid-execution. RadSSH does stdout/stderr reads with a limited timeout, and it should be possible to check connection health when the timeouts occur, and handle dropped connections appropriately. At least that's what I'm hoping for.

**Comment by radssh** [comment]
This is more of a challenge than anticipated. Will leave open and continue investigating, but this potential fix will not make the upcoming 1.0.5 release.
