### ISSUE TITLE
Upgraded to 1.1.2 and it broke me

### ISSUE THREAD

**Issue by tynin** [radssh/radssh#37]
Upgraded radssh:

> sudo pip install --upgrade radssh
> WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
> Collecting radssh
>   Downloading https://files.pythonhosted.org/packages/bb/51/94caae590ad6b790b7933aac4bad863874ff7a66b582d51dcaf243542c10/radssh-1.1.2-py2-none-any.whl (81kB)
>     100% |████████████████████████████████| 92kB 813kB/s 
> Requirement already up-to-date: netaddr in /usr/lib/python2.7/site-packages (from radssh)
> Collecting paramiko (from radssh)
>   Downloading https://files.pythonhosted.org/packages/3e/db/cb7b6656e0e7387637ce850689084dc0b94b44df31cc52e5fc5c2c4fd2c1/paramiko-2.4.1-py2.py3-none-any.whl (194kB)
>     100% |████████████████████████████████| 194kB 713kB/s 
> Collecting cryptography>=1.5 (from paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/dd/c2/3a5bfefb25690725824ade71e6b65449f0a9f4b29702cce10560f786ebf6/cryptography-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
>     100% |████████████████████████████████| 2.2MB 431kB/s 
> Collecting pynacl>=1.0.1 (from paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/80/3d/d709b9fbd69e21dd3a4d34eb690c5484094699e03b7447bc7eb173cfd7b6/PyNaCl-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (696kB)
>     100% |████████████████████████████████| 706kB 403kB/s 
> Collecting pyasn1>=0.1.7 (from paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl (72kB)
>     100% |████████████████████████████████| 81kB 803kB/s 
> Collecting bcrypt>=3.1.3 (from paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/2e/5a/2abeae20ce294fe6bf63da0e0b5a885c788e1360bbd124edcc0429678a59/bcrypt-3.1.4-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
>     100% |████████████████████████████████| 61kB 489kB/s 
> Collecting idna>=2.1 (from cryptography>=1.5->paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
>     100% |████████████████████████████████| 61kB 371kB/s 
> Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.5->paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl (407kB)
>     100% |████████████████████████████████| 409kB 614kB/s 
> Requirement already up-to-date: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko->radssh)
> Requirement already up-to-date: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko->radssh)
> Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.5->paramiko->radssh)
> Collecting ipaddress; python_version < "3" (from cryptography>=1.5->paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
> Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.5->paramiko->radssh)
>   Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
>     100% |████████████████████████████████| 256kB 624kB/s 
> Installing collected packages: idna, pycparser, cffi, ipaddress, cryptography, pynacl, pyasn1, bcrypt, paramiko, radssh
>   Found existing installation: idna 2.5
>     Uninstalling idna-2.5:
>       Successfully uninstalled idna-2.5
>   Found existing installation: pycparser 2.17
>     Uninstalling pycparser-2.17:
>       Successfully uninstalled pycparser-2.17
>   Running setup.py install for pycparser ... done
>   Found existing installation: cffi 1.11.2
>     Uninstalling cffi-1.11.2:
>       Successfully uninstalled cffi-1.11.2
>   Found existing installation: ipaddress 1.0.18
>     Uninstalling ipaddress-1.0.18:
>       Successfully uninstalled ipaddress-1.0.18
>   Found existing installation: cryptography 2.2.1
>     Uninstalling cryptography-2.2.1:
>       Successfully uninstalled cryptography-2.2.1
>   Found existing installation: pyasn1 0.3.7
>     Uninstalling pyasn1-0.3.7:
>       Successfully uninstalled pyasn1-0.3.7
>   Found existing installation: paramiko 2.1.2
>     Uninstalling paramiko-2.1.2:
>       Successfully uninstalled paramiko-2.1.2
>   Found existing installation: radssh 1.1.1
>     Uninstalling radssh-1.1.1:
>       Successfully uninstalled radssh-1.1.1
> Successfully installed bcrypt-3.1.4 cffi-1.11.5 cryptography-2.2.2 idna-2.6 ipaddress-1.0.22 paramiko-2.4.1 pyasn1-0.4.3 pycparser-2.18 pynacl-1.2.1 radssh-1.1.2
> 

Then attempted to radssh to a server:

> python -m radssh.shell x.x.x.x
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/usr/lib/python2.7/site-packages/radssh/shell.py", line 40, in <module>
>     import paramiko
>   File "/usr/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
>     from paramiko.transport import SecurityOptions, Transport
>   File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>
>     from paramiko.auth_handler import AuthHandler
>   File "/usr/lib/python2.7/site-packages/paramiko/auth_handler.py", line 48, in <module>
>     from paramiko.ssh_gss import GSSAuth, GSS_EXCEPTIONS
>   File "/usr/lib/python2.7/site-packages/paramiko/ssh_gss.py", line 54, in <module>
>     GSS_EXCEPTIONS = (gssapi.GSSException,)
> AttributeError: 'module' object has no attribute 'GSSException'
> 

Downgrading paramiko back to 2.1.2 resolved the issue:

> sudo pip install paramiko==2.1.2 --force
> WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
> Collecting paramiko==2.1.2
>   Downloading https://files.pythonhosted.org/packages/14/1e/2988f842e3194daf4d6e14e6e38e8d7085b2b45c669c3b635708c4a7618c/paramiko-2.1.2-py2.py3-none-any.whl (172kB)
>     100% |████████████████████████████████| 174kB 428kB/s 
> Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python2.7/site-packages (from paramiko==2.1.2)
> Requirement already satisfied: cryptography>=1.1 in /usr/lib64/python2.7/site-packages (from paramiko==2.1.2)
> Requirement already satisfied: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.1.2)
> Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/lib64/python2.7/site-packages (from cryptography>=1.1->paramiko==2.1.2)
> Requirement already satisfied: enum34; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.1.2)
> Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.1.2)
> Requirement already satisfied: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.1.2)
> Requirement already satisfied: ipaddress; python_version < "3" in /usr/lib/python2.7/site-packages (from cryptography>=1.1->paramiko==2.1.2)
> Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.1->paramiko==2.1.2)
> Installing collected packages: paramiko
>   Found existing installation: paramiko 2.4.1
>     Uninstalling paramiko-2.4.1:
>       Successfully uninstalled paramiko-2.4.1
> Successfully installed paramiko-2.1.2
> 

Now it works:

> python -m radssh.shell x.x.x.x
> *** Ludicrous Speed ***
> Connecting to 1 hosts...
> .
> RadSSH $ 
> Shell exiting

**Comment by radssh** [comment]
Seems to be an underlying Paramiko issue dealing with simultaneously supporting two different GSSAPI modules. See[ paramiko#1069 ](https://github.com/paramiko/paramiko/issues/1069)  and [paramiko#1068](https://github.com/paramiko/paramiko/issues/1068). Can be addressed with downgrading Paramiko, as you have done, or isolating the "right" gssapi module as outlined in the Paramiko issues.
