### ISSUE TITLE
Username prefrence override

### ISSUE THREAD

**Issue by Arlion** [radssh/radssh#39]
```
~/.ssh/config
host *
        user arlion
```

```
python -m radssh.shell --username=notarlion 192.168.0.1

RadSSH $ *info
*** Cluster Status ***
 192.168.0.1 : (  0.993s) Authenticated as arlion to 192.168.0.1
```

I request that the --username flag overrides ~/.ssh/config and will use the username specified in the command line as the de facto method of username login.

Expected behavior:

```
python -m radssh.shell --username=notarlion 192.168.0.1

RadSSH $ *info
*** Cluster Status ***
 192.168.0.1 : (  0.993s) Authenticated as notarlion to 192.168.0.1
```

**Comment by radssh** [comment]
The current application of command line parameters (--keyword=value) is to override options set in the radssh.config, but the adding of ssh_config processing applies those options at a higher precedence. There is a placeholder issue (#35) to add (-o SSH_Option=value) to the command line processing, which would naturally be the ultimate option override (highest precedence).
Not sure (yet) of the reordering of the precedence of --keyword=value options versus ssh_config options, as right now, --keyword=value effectively allows override of the radssh.config settings without having to edit/save the config file, and the ssh_config options are higher precedence than any in radssh.config.

**Comment by radssh** [comment]
Roll into #35 - slated for 2.0
