### ISSUE TITLE
*sftp and *run Local tab completion

### ISSUE THREAD

**Issue by jacob0** [radssh/radssh#4]
Hi,

I enjoy the tab completion feature but wonder if the *sftp and *run commands could tab-complete for local files. Dropping into a local subshell using *sh works fine, but this could be faster and perhaps more natural.

Thanks,

Jacob

**Comment by radssh** [comment]
Currently the tab completion is set to resolve file and directories from a representative remote host filesystem, under the assumption that the directories and files are predominantly the same or similar across all the hosts connected to for the current session. Based on your information, I can see some instances where resolving against the local (client) filesystem makes more sense for **\*run** and **\*sftp** specifically, as well as some other **\*commands**.

It seems that local filesystem completion only makes sense for **\*commands**, and even then, only for some, and still further, only for certain positions of arguments (**\*run** and **\*sftp** would only resolve locally for the first positional argument, I would think). Adding in a local filesystem resolver option would in fact be easier than the slightly tricky remote filesystem resolver that is currently implemented, but the trickier part will be smartly handling the situations where choosing between local and remote is done, and probably allowing the plugins themselves to dictate when switching to local is preferred.

This will need some further investigation as far as how to implement, and may need some reworking of the plugin interface for **\*commands** for the plugins that would need to take advantage. No timetable, but this can be expected to be added as an enhancement in a future release.
