### ISSUE TITLE
add -i key_file to cmdline

### ISSUE THREAD

**Issue by mckellyln** [radssh/radssh#42]
It would be nice if radssh accepted the -i keyfile cmdline arguments to be similar to ssh
As it is now I can create a .radssh_auth file and put keyfile in that, but still nice if radssh mirrored ssh here.

**Comment by mckellyln** [comment]
NOTE this is an alternate solution to supporting a new username filter in the .radssh_auth file.

**Comment by radssh** [comment]
Roll into #35 - 2.0 target
