### ISSUE TITLE
RadSSH should take advantage of user & system SSH Config option settings

### ISSUE THREAD

**Issue by radssh** [radssh/radssh#6]
Through Paramiko SSHConfig, RadSSH should make use of settings from /etc/ssh/ssh_config and ~/.ssh/config. This would give greated flexibility and conform better to existing environments that may have elaborate config settings per host, as well as unify the settings for things like host key verification handling.

**Comment by mf-lit** [comment]
I'd also like to see this, most of the hosts have alias-names defined in ~/.ssh/config and also proxy through other hosts.

**Comment by radssh** [comment]
Released (finally) in 1.1.0 for many options. If an important one is not included, please open new issue.
