### ISSUE TITLE
grep, match, nomatch commands should search text in stderr as well as stdout

### ISSUE THREAD

**Issue by seekamp** [radssh/radssh#7]
The *grep, *match, *nomatch commands currently only look at stdout. I have encountered situations where the text I need to look for is in stderr instead.  Can you please update the commands to look at stderr as well? If I wanted to exclude either stderr or stdout for a particular command, I could redirect that type of output to /dev/null.  Thanks.

**Comment by radssh** [comment]
I don't see any compelling reason to exclude stderr from being included as source data to match for these commands. Considering that when commands are run under force_tty, stderr is merged with, and indistinguishable from stdout. To try to keep consistent behavior, I think the plugin should always scan both stdout and stderr for matching (or not matching).
